# **1. Searching 101**

Write a program that solicits six (6) numbers from the user and prints a message that describes whether the sixth number appears among the first five.

## Inputs/outputs 

input/s:
* Six numbers from user

outputs:
* sentence printed saying whether last number is included


## Problem domain

## Implicit Requirements

* Number only has to have been included once, but can be included more

## Clarifying Questions

DO we have to account for negative numbers?
* We will allow them
Do we accept floating point numbers?
* No 

## Mental Model

Take 6 numbers from the user and print a string saying whether the final input number was included in the five beforehand.

## Examples/Test Cases

```
Enter the 1st number: 25
Enter the 2nd number: 15
Enter the 3rd number: 20
Enter the 4th number: 17
Enter the 5th number: 23
Enter the last number: 17

17 is in 25,15,20,17,23.
```


```
Enter the 1st number: 25
Enter the 2nd number: 15
Enter the 3rd number: 20
Enter the 4th number: 17
Enter the 5th number: 23
Enter the last number: 18

18 isn't in 25,15,20,17,23.
```

## Data/Algorithm

Create empty list: nums_list
Get first 5 numbers from user, adding each to num_list
Set last_num to input from user

print out whether last_num is in nums_list

In [4]:
nums_list = []

nums_list.append(input("Enter the 1st number:  "))
nums_list.append(input("Enter the 2nd number:  "))
nums_list.append(input("Enter the 3rd number:  "))
nums_list.append(input("Enter the 4th number:  "))
nums_list.append(input("Enter the 5th number:  "))

last_num = input("Enter the last number: ")

if last_num in nums_list:
    print(f"{last_num} is in {",".join(nums_list)}.")
else:
    print(f"{last_num} isn't in {",".join(nums_list)}.")

Enter the 1st number:   1
Enter the 2nd number:   2
Enter the 3rd number:   3
Enter the 4th number:   4
Enter the 5th number:   5
Enter the last number:   6


6 isn't in 1,2,3,4,5.


## **2. Palindromic Strings (Part 1)**

Write a function that returns True if the string passed as an argument is a palindrome, False otherwise. 
A palindrome reads the same forwards and backwards. For this problem, the case matters and all characters matter.
Examples



## Input/Outputs

Inputs:
* string

Outputs:
* Boolean value, True if input is palindrome, False otherwise.

## Problem Domain

String is a palindrome when the same string reversed exactly equals the initial string

## Implicit Requirements

* Numbers, and non alphabetical characters can be in input string.
* All characters must be identical both ways

## Examples/Test Cases


All of these examples should print True

```python
print(is_palindrome('madam') == True)
print(is_palindrome('356653') == True)
print(is_palindrome('356635') == False)
```


case matters
```python
print(is_palindrome('Madam') == False)
```

all characters matter
```python
print(is_palindrome("madam i'm adam") == False)
```

## Mental Model

Return True if string is same backwards as forwards, otherwise return False

## Data/Algorithm

is_palindrome function, input: input_str
* Set input_reversed to reversed input_str
* Return True if equal otherwise False

In [9]:
def is_palindrome(input_str):
    input_reversed = input_str[::-1]

    print(input_str, input_reversed)
    return (input_str == input_reversed)

print(is_palindrome('madam') == True)
print(is_palindrome('356653') == True)
print(is_palindrome('356635') == False)

madam madam
True
356653 356653
True
356635 536653
True


## **3. Palindromic Strings (Part 2)**

Write another function that returns True if the string passed as an argument is a palindrome, or False otherwise. 
This time, however, your function should be case-insensitive, and should ignore all non-alphanumeric characters. 
If you wish, you may simplify things by calling the is_palindrome function you wrote in the previous exercise.

## Inputs/Outputs

Input:
* string

Output:
* boolean 

## Examples/Test Cases

```python
print(is_real_palindrome('madam') == True)           # True
print(is_real_palindrome('356653') == True)          # True
print(is_real_palindrome('356635') == False)         # True
print(is_real_palindrome('356a653') == True)         # True
print(is_real_palindrome('123ab321') == False)       # True

# case doesn't matter
print(is_real_palindrome('Madam') == True)           # True

# only alphanumerics matter
print(is_real_palindrome("Madam, I'm Adam") == True) # True
```

## Data/Algorithm

Convert input string to all lowercase.

Remove all non-alphanumeric characters

Use is_palindrome function

In [14]:
def is_palindrome(input_str):
    input_reversed = input_str[::-1]

    print(input_str, input_reversed)
    return (input_str == input_reversed)



def only_aplhanum(input_str):
    output_str = ""

    for char in input_str:
        if char.isalnum():
            output_str += char

    return output_str
                  


def is_real_palindrome(input_str):
    cleaned_str = only_aplhanum(input_str.lower())

    return cleaned_str == cleaned_str[::-1]




print(is_real_palindrome('madam') == True)           # True
print(is_real_palindrome('356653') == True)          # True
print(is_real_palindrome('356635') == False)         # True
print(is_real_palindrome('356a653') == True)         # True
print(is_real_palindrome('123ab321') == False)       # True

# case doesn't matter
print(is_real_palindrome('Madam') == True)           # True

# only alphanumerics matter
print(is_real_palindrome("Madam, I'm Adam") == True) # True

True
True
True
True
True
True
True


# **4. Running Totals**

Write a function that takes a list of numbers and returns a list with the same number of elements, 
but with each element's value being the running total from the original list.

## Inputs/Outputs

Inputs:
* List containing numbers

Output:
* List containing same number of elements, with a runnign total of the original elements being added

## Implicit Requirements

* Empty list as input should return an empty list
* Input of length 1 returns itself

## Examples/Test Cases

```python 
print(running_total([2, 5, 13]) == [2, 7, 20])    # True
print(running_total([14, 11, 7, 15, 20])
      == [14, 25, 32, 47, 67])                    # True
print(running_total([3]) == [3])                  # True
print(running_total([]) == [])                    # True
```

## Data/Algorithm

Unneccessary for this problem

In [15]:
def running_total(input_list):
    output_list = []
    running_total = 0

    for num in input_list:
        running_total += num
        output_list.append(running_total)

    return output_list

print(running_total([2, 5, 13]) == [2, 7, 20])    # True
print(running_total([14, 11, 7, 15, 20])
      == [14, 25, 32, 47, 67])                    # True
print(running_total([3]) == [3])                  # True
print(running_total([]) == [])                    # True

True
True
True
True


# **5. Letter Counter**

Write a function that takes a string consisting of zero or more space-separated words and 
returns a dictionary that shows the number of words of different sizes.

Words consist of any sequence of non-space characters.

## Input/Output

Input:
* String of any size

Output: 
* Dictionary, containing word lengths as keys and frequency of those lengths as values

## Implicit Requirements

* In output dictionary only include keys, whose length is actually represented in the input
* Punctuation adds to word length

## Clarifying Questions
N/A


## Mental Model

Take a string of any length as input, return a dictionary containing the frequency of different word lengths in the input string. Only add keys for word lengths which appear in input.

## Examples/Test Cases

```python 
# All of these examples should print True

string = 'Four score and seven.'
print(word_sizes(string) == {4: 1, 5: 1, 3: 1, 6: 1})

string = 'Hey diddle diddle, the cat and the fiddle!'
print(word_sizes(string) == {3: 5, 6: 1, 7: 2})

string = 'Humpty Dumpty sat on a wall'
print(word_sizes(string) == {6: 2, 3: 1, 2: 1, 1: 1, 4: 1})

string = "What's up doc?"
print(word_sizes(string) == {6: 1, 2: 1, 4: 1})

print(word_sizes('') == {}) 
```

## Data/Algorithm

Set words_list to input_list separated

Set list_of_lengths to words_list transformed

Set dict_length frequency to empty dictionary

Iterate over list_of_lengths:
* If length does not exist as key of dict_length_frequency:
    * add key with value 1
* If it does exist:
    * Add 1 to val
* return dict_length_frequency

In [19]:
def word_sizes(input_string):
    words_list = input_string.split()
    list_of_lengths = [len(word) for word in words_list]
    dict_length_frequency = {}

    for length in list_of_lengths:
        dict_length_frequency[length] = (dict_length_frequency.get(length, 0) + 1)

    return dict_length_frequency

string = 'Four score and seven.'
print(word_sizes(string) == {4: 1, 5: 1, 3: 1, 6: 1})

string = 'Hey diddle diddle, the cat and the fiddle!'
print(word_sizes(string) == {3: 5, 6: 1, 7: 2})

string = 'Humpty Dumpty sat on a wall'
print(word_sizes(string) == {6: 2, 3: 1, 2: 1, 1: 1, 4: 1})

string = "What's up doc?"
print(word_sizes(string) == {6: 1, 2: 1, 4: 1})

True
True
True
True


# **6. Letter Counter (Part 2)**

Modify the word_sizes function from the previous exercise to exclude non-letters when determining word size. 
For instance, the word size of "it's" is 3, not 4.




## Examples/Test Cases

```python
# All of these examples should print True

string = 'Four score and seven.'
print(word_sizes(string) == {4: 1, 5: 2, 3: 1})

string = 'Hey diddle diddle, the cat and the fiddle!'
print(word_sizes(string) == {3: 5, 6: 3})

string = 'Humpty Dumpty sat on a w@ll'
print(word_sizes(string) == {6: 2, 3: 2, 2: 1, 1: 1})

string = "What's up doc?"
print(word_sizes(string) == {5: 1, 2: 1, 3: 1})

print(word_sizes('') == {}) 

```

## Data/Algorithm

Create new string cleaner function that remove non alphabetic/white space characters]

Set new string:
* Loop over characters in input_str
* If char is alphanumeirc or white space
    * Add to new_string


In [3]:
def clean_str(input_str): 
    new_str = ""

    for char in input_str:
        if char.isalnum() or (char == " "):
            new_str += char

    return new_str

def word_sizes(input_string):
    input_string = clean_str(input_string)
    
    words_list = input_string.split()
    list_of_lengths = [len(word) for word in words_list]
    dict_length_frequency = {}

    for length in list_of_lengths:
        dict_length_frequency[length] = (dict_length_frequency.get(length, 0) + 1)

    return dict_length_frequency



string = 'Four score and seven.'
print(word_sizes(string) == {4: 1, 5: 2, 3: 1})

string = 'Hey diddle diddle, the cat and the fiddle!'
print(word_sizes(string) == {3: 5, 6: 3})

string = 'Humpty Dumpty sat on a w@ll'
print(word_sizes(string) == {6: 2, 3: 2, 2: 1, 1: 1})

string = "What's up doc?"
print(word_sizes(string) == {5: 1, 2: 1, 3: 1})

print(word_sizes('') == {}) 

True
True
True
True
True


# **7. Letter Swap**

Given a string of words separated by spaces, write a function that swaps the first and last letters of every word.

You may assume that every word contains at least one letter, and that the string will always contain at least one word. 
You may also assume that each string contains nothing but words and spaces, and that there are no leading, trailing, or repeated spaces.

## Input/Output

Input: 
* String of words separated by spaces

Output: 
* String containing the same words with first and last letters swapped


## Implicit Requirements

Words are in same order in output as with the input

## Clarifying Questions


Do we ignore case?
* Yes


## Mental Model 

Take a string containign at least one word, with more words separated by spaces. 
Return a new string with the words in the same order, except the fast and last letter of each word are swapped

## Examples/Test Cases 
```python 
print(swap('Oh what a wonderful day it is')
      == "hO thaw a londerfuw yad ti si")  # True
print(swap('Abcde') == "ebcdA")            # True
print(swap('a') == "a")                    # True
``` 

## Data/Algorithm

function, swap: string input
Set words_list to list of words contained in input_str
Set output_str to empty string
Iterate through words in words_list
* set word_to_add to letter swapped word
* Add word_to_add and space to output_str
Removed trailing white space from right o f output_str
Return output_str

In [14]:


def swap(input_str): 
    words_list = input_str.split()
    output_str = ""

    for word in words_list:
        if len(word) == 1:
            output_str += (word + " ")
        else:
            output_str += word[-1] + word[1:-1] + word[0] + " "
    
    output_str = output_str.rstrip()

    return output_str


print(swap('Oh what a wonderful day it is')
      == "hO thaw a londerfuw yad ti si")  # True
print(swap('Abcde') == "ebcdA")            # True
print(swap('a') == "a")                    # True

True
True
True


# **8. Convert String to a Number** 

Write a function that takes a string of digits and returns the appropriate number as an integer. 
You may not use any of the standard conversion functions available in Python, such as int. 
Your function should calculate the result by using the characters in the string.

For now, do not worry about leading + or - signs, nor should you worry about invalid characters; assume all characters are numeric.

## Input/Output

Input: 
* String containing only digits

Output: 
* Integer representing same number as input string

## Problem Domain

N/A 

## Implicit Requirements 

* Works for strings of varying lengths

## Mental Model

For each num char in string multiply it by num of chars in string - 1

## Examples/Test Cases

```python 
print(string_to_integer("4321") == 4321)  # True
print(string_to_integer("570") == 570)    # True
```


"507"

## Data/Algorithm

Set conversion_dict to dictionary m,apping characters to integers

* Set output_num to zero
* Set num_to_multiply to length of input - 1
* Iterate over char_nums of input_str
    * set digit_int using conversion_dict
    * Iterate num_to_muliply times:
        * reassign digit_into to itself * 10
    * Take away one from num_to_multiply
    * Add digit_int to output_num

In [17]:
COVERSION_DICT = {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "0": 0,
}


def string_to_integer(input_str):
    output_num = 0
    num_to_multiply = len(input_str) - 1

    for char_num in input_str:
        digit_int = COVERSION_DICT[char_num]

        for _ in range(num_to_multiply):
            digit_int *= 10

        num_to_multiply -= 1

        output_num += digit_int

    return output_num



print(string_to_integer("4321") == 4321)  # True
print(string_to_integer("570") == 570)    # True

True
True


## Further Exploration

Write a hexadecimal_to_integer function that converts a string representing a hexadecimal number to its integer value. 
Hexadecimal numbers use base 16 instead of 10, and the characters A, B, C, D, E and F (and the lowercase equivalents) 
correspond to decimal values of 10-15.
Example

```python
print(hexadecimal_to_integer('4D9f') == 19871)  # True
```

In [21]:
COVERSION_DICT = {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "a": 10,
    "b": 11,
    "c": 12,
    "d": 13,
    "e": 14,
    "f": 15,
    "0": 0,
}


def hexadecimal_to_integer(input_str):
    output_num = 0
    num_to_multiply = len(input_str) - 1
    input_str = input_str.lower()

    for char_num in input_str:
        digit_int = COVERSION_DICT[char_num]

        for _ in range(num_to_multiply):
            digit_int *= 16

        num_to_multiply -= 1

        output_num += digit_int

    return output_num



print(hexadecimal_to_integer('4D9f') == 19871)


True


# **9. Convert a String to a Signed Number**

In the previous exercise, you developed a function that converts simple numeric strings to integers. 
In this exercise, you're going to extend that function to work with signed numbers.

Write a function that takes a string of digits and returns the appropriate number as an integer. 
The string may have a leading + or - sign; if the first character is a +, your function should return a positive number; 
if it is a -, your function should return a negative number. If there is no sign, return a positive number.

You may assume the string will always contain a valid number.

You may not use any of the standard conversion functions available in Python, such as int. You may, however, use the string_to_integer function from the previous exercise.

## Input/Output

Input: 
* String containing a number, with an optioonal prefix of "-" or "+ to represent sign

Output:
* Integer represantation of input number

## Data/Algorithm

get_sign, helpter function:
if first element is numeric or equal to "+":
    * return "+"
else:
    * return "-"

Main function:
set sign to sign from get_sign

if first element is not numeric:
* remove first element
Use function to set output_num
if sign is "+":
* return output_num
else:
* return output_num * -1

## Examples/Test Cases

```python
print(string_to_signed_integer("4321") == 4321)  # True
print(string_to_signed_integer("-570") == -570)  # True
print(string_to_signed_integer("+100") == 100)   # True
```

In [ ]:
COVERSION_DICT = {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "0": 0,
}


def string_to_integer(input_str):
    output_num = 0
    num_to_multiply = len(input_str) - 1

    for char_num in input_str:
        digit_int = COVERSION_DICT[char_num]

        for _ in range(num_to_multiply):
            digit_int *= 10

        num_to_multiply -= 1

        output_num += digit_int

    return output_num

def get_sign_from_string(input_str):
    first_char = input_str[0]

    if (first_char == "+") or first_char.isnumeric():
        return "+"
    else:
        return "-"

print(get_sign_from_string("-120"))


def string_to_signed_integer(num_as_string):
    sign = get_sign_from_string(num_as_string)

    if not num_as_string[0].isnumeric():
        num_as_string = num_as_string[1:]

    output_num = string_to_integer(num_as_string)

    if sign == "+":
        return output_num
    else:
        return output_num * -1


print(string_to_signed_integer("4321") == 4321)  # True
print(string_to_signed_integer("-570") == -570)  # True
print(string_to_signed_integer("+100") == 100)   # True

# **10. Convert a Number to a String**

In the previous two exercises, you developed functions that convert simple numeric strings to signed integers. 
In this exercise and the next, you're going to reverse those functions.

Write a function that converts a non-negative integer value (e.g., 0, 1, 2, 3, and so on) to the string representation of that integer.

You may not use any of the standard conversion functions available in Python, such as str. 
Your function should do this the old-fashioned way and construct the string by analyzing and manipulating the number.

## Input/Output

Input:
* Non-negative integer

Output:
* String representation of input integer

## Problem Domain

What is a non-negative integer?
* An integer 0 or greater

## Implicit Requirements

Return 0 as string "0"



## Clarifying Questions

N/A

## Examples/Test Cases

```python 
print(integer_to_string(4321) == "4321")              # True
print(integer_to_string(0) == "0")                    # True
print(integer_to_string(5000) == "5000")              # True
print(integer_to_string(1234567890) == "1234567890")  # True
```

## Mental Model

Take an integer of 0 or greater as input, and return the integer as a string

## Data/Algorithm

Set constant CONVERSION_DICT

function: integer_to_string: input_int
if input_int equals 0:
* return string "0"

set output_str to empty string

Loop while input_int does not equal zero:
* set num_to_remove to last digit of input_int
* set num_as_char: convert using CONVERSION_DICT
* Add num_as_char to first element for output_str
* reassign input_int to floor division by 10

return output_str

In [44]:
COVERSION_DICT = {
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    0: "0",
}



def integer_to_string(input_int):
    if input_int == 0:
        return "0"

    output_str = ""
    
    while input_int != 0:
        num_to_remove = input_int % 10
        num_as_char = COVERSION_DICT[num_to_remove]

        output_str = num_as_char + output_str

        input_int = input_int // 10

    return output_str



print(integer_to_string(4321) == "4321")              # True
print(integer_to_string(0) == "0")                    # True
print(integer_to_string(5000) == "5000")              # True
print(integer_to_string(1234567890) == "1234567890")  # True

True
True
True
True


# **11. Covert a Signed Number to a String**

In the previous exercise, you developed a function that converts non-negative numbers to strings. 
In this exercise, you're going to extend that function by adding the ability to represent negative numbers as well.

Write a function that takes an integer and converts it to a string representation.

You may not use any of the standard conversion functions available in Python, such as str. 
You may, however, use integer_to_string from the previous exercise.

## Input/Output

Input:
* Any integer

Output:
* String representation of input, containing prefix of sign if relevant

In [40]:
## Examples/Test Cases

```
print(signed_integer_to_string(4321) == "+4321")  # True
print(signed_integer_to_string(-123) == "-123")   # True
print(signed_integer_to_string(0) == "0")         # True
```

SyntaxError: invalid syntax (961582235.py, line 3)

## Data/Algorithm

Helper function: integer_to_str:
* Same as previous excercise

Function, signed_integer to string:
* Set string_without_sign using helper function
* if input_int is 0:
    * return string_without_sign
* else if input int is positive:
    * Return string with "+" as prefix
* if input_int is negative
    * Return string with "-" as prefix 

In [2]:
COVERSION_DICT = {
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    0: "0",
}



def integer_to_string(input_int):
    if input_int == 0:
        return "0"

    output_str = ""
    
    while input_int != 0:
        num_to_remove = input_int % 10
        num_as_char = COVERSION_DICT[num_to_remove]

        output_str = num_as_char + output_str

        input_int = input_int // 10

    return output_str

def signed_integer_to_string(input_int):
    string_without_sign = integer_to_string(abs(input_int))

    if input_int == 0:
        return string_without_sign
    elif input_int < 0:
        return "-" + string_without_sign
    else:
        return "+" + string_without_sign



print(signed_integer_to_string(4321) == "+4321")  # True
print(signed_integer_to_string(-123) == "-123")   # True
print(signed_integer_to_string(0) == "0")         # True

True
True
True
